export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const SET_BUN = 'SET_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SWAP_INGREDIENTS = 'SWAP_INGREDIENTS';
export const CLEAR_CONSTRUCTOR_DATA = 'CLEAR_CONSTRUCTOR_DATA'

