export const SHOW_INGREDIENTS_ERROR = 'SHOW_INGREDIENTS_ERROR';
export const SHOW_INGREDIENTS = 'SHOW_INGREDIENTS';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT';
export const CLEAR_ITEM_COUNT = 'CLEAR_ITEM_COUNT';