export const SHOW_INGREDIENTS_ERROR = 'SHOW_INGREDIENTS_ERROR';
export const SHOW_INGREDIENTS_SUCCESS = 'SHOW_INGREDIENTS_SUCCESS';
export const SHOW_INGREDIENTS_REQUEST = 'SHOW_INGREDIENTS_REQUEST';
export const INCREASE_ITEM_COUNT = 'INCREASE_ITEM_COUNT';
export const DECREASE_ITEM_COUNT = 'DECREASE_ITEM_COUNT';
export const CLEAR_ITEM_COUNT = 'CLEAR_ITEM_COUNT';