export const SHOW_ORDER_NUMBER_REQUEST = 'SHOW_ORDER_NUMBER_REQUEST';
export const SHOW_ORDER_NUMBER_SUCCESS = 'SHOW_ORDER_NUMBER_SUCCESS';
export const SHOW_ORDER_NUMBER_ERROR = 'SHOW_ORDER_NUMBER_ERROR';
export const CLEAR_ORDER_NUMBER = 'CLEAR_ORDER_NUMBER';