export const SET_REGISTRATION_REQUEST = 'SET_REGISTRATION_REQUEST';
export const SET_REGISTRATION_SUCCESS = 'SET_REGISTRATION_SUCCESS';
export const SET_REGISTRATION_ERROR = 'SET_REGISTRATION_ERROR';
