export const SET_FORGOT_PASSWORD_REQUEST = 'SET_FORGOT_PASSWORD_REQUEST';
export const SET_FORGOT_PASSWORD_SUCCESS = 'SET_FORGOT_PASSWORD_SUCCESS';
export const SET_FORGOT_PASSWORD_FAILED = 'SET_FORGOT_PASSWORD_FAILED';

export const SET_RESET_PASSWORD_REQUEST = 'SET_FORGOT_PASSWORD_REQUEST';
export const SET_RESET_PASSWORD_SUCCESS = 'SET_FORGOT_PASSWORD_SUCCESS';
export const SET_RESET_PASSWORD_FAILED = 'SET_FORGOT_PASSWORD_FAILED';

export const SET_REGISTER_REQUEST = 'SET_REGISTER_REQUEST';
export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILED = 'SET_REGISTER_FAILED';

export const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED';

export const SET_LOGOUT_REQUEST = 'SET_LOGOUT_REQUEST';
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS';
export const SET_LOGOUT_FAILED = 'SET_LOGOUT_FAILED';

export const SET_USER_REQUEST = 'SET_USER_REQUEST';
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_FAILED = 'SET_USER_FAILED';

export const SET_TOKEN_REQUEST = 'SET_TOKEN_REQUEST';
export const SET_TOKEN_SUCCESS = 'SET_TOKEN_SUCCESS';
export const SET_TOKEN_FAILED = 'SET_TOKEN_FAILED';

export const SET_USER_UPDATE_REQUEST = 'SET_USER_UPDATE_REQUEST';
export const SET_USER_UPDATE_SUCCESS = 'SET_USER_UPDATE_SUCCESS';
export const SET_USER_UPDATE_FAILED = 'SET_USER_UPDATE_FAILED';